allowBuilds:
  '@parcel/watcher': true
  '@percy/core': true
  cypress: true
  esbuild: true
  protobufjs: true
  unrs-resolver: true
  vue-demi: true
engineStrict: true
minimumReleaseAge: 0 # pnpm 11 changes this to prevent installing versions less than 24 hours old, we want to allow all versions
