fragment BlockImpactNumbersCarouselFragment on ElementInterface {
    id
    impactNumbersCarousel {
        id
        ... on impactNumbersCarousel_impactNumbersCarousel_BlockType {
            largeText: impactNumber
            mediumText: impactText
            smallDescriptor: summary
            image {
                ...Image
            }
        }
    }
}
