fragment BlockCtaBlockTwoUp on ElementInterface {
    id
    text: shortDescription
    name: urlButtonText
    to: urlButtonUrl
    title: titleCTA2Up
    svgName: icon
    backgroundColor
    isSizeSmall
}
