fragment BlockHighlight on ElementInterface {
    id
    contentLink {
        id
        url
        to: uri
        title
        prompt: buttonText
        text: shortDescription
        date {
            startDate
            endDate
        }
        associatedLocations {
            id
            title
            to: uri
        }
        heroImage {
            ... on heroImage_heroImage_BlockType {
                id
                image {
                    ...Image
                }
                altText
            }
        }
    }
}
