fragment BlockBannerFeaturedFragment on ElementInterface {
    typeHandle
    id
    titleGeneral
    meapflexiblePageBlocks_bannerFeatured {
        ... on meapflexiblePageBlocks_bannerFeatured_internalContent_BlockType {
            id
            contentLink {
                contentType: sectionHandle
                title
                to: uri
                summary
                projectCategory: format
                eventCategory: eventType
                articleCategory: articleCategories
                projectByline1: meapProjectTopic {
                    ... on meapProjectTopics_Category {
                        title
                    }
                }
                articleByline1: staffMember {
                  id
                  slug
                  title
                }
                articleByline2: date
                eventByline1: dateStartTime
                eventByline2: dateEndTime

                articleLocations: associatedLocations {
                    id
                    title
                    to: uri
                }
                eventLocations: eventLocation
                projectLocations: region
                # aligment will be defualts to left
                heroImage {
                    ... on heroImage_heroImage_BlockType {
                        image {
                            ...Image
                        }
                    }
                }
            }
        }
        ... on meapflexiblePageBlocks_bannerFeatured_externalContent_BlockType {
            id
            image {
                ...Image
            }
            titleGeneral
            title
            summary
            alignment
            location
            byline1
            byline2
            to: buttonUrl
            category
            contentType
        }
    }
}
