query FooterSponsor {
  globalSets {
    ... on meapFunders_GlobalSet {
        funders {
            ... on funders_funder_BlockType {
            id
            funderLogo {
                ... on mediaAndDocuments_Asset {
                img
                }
            }
            alt: funderName
            to: funderUrl
            }
        }
        }
    }
}
