#import "~/gql/fragments/MenuItem"
#import "~/gql/fragments/Image"

query FooterMenuItems {
  sponsors: globalSets {
    ... on meapFunders_GlobalSet {
      id
      name
      funders {
        ... on funders_funder_BlockType {
          id
          funderName
          funderLogo {
            id
            ... on mediaAndDocuments_Asset {
              ...Image
            }
          }
          funderUrl
        }
      }
    }
  }
  primary: nodes(navHandle: "footerSockLinks", level: 1) {
    ...MenuItem
  }
  sock: nodes(navHandle: "footerPrimary", level: 1) {
    ...MenuItem
    children {
      ...MenuItem
    }
  }
}
