#import "~/gql/fragments/Image"

query NewsListingPage {
    entries(section: "meapListingNews") {
        ... on meapListingNews_meapListingNews_Entry {
            id
            title: titleGeneral
            summary
            meapNewsListing {
                id
                title
                text: summary
                authors: staffMember {
                    id
                    slug
                    title
                }
                category: articleCategories {
                    title
                }
                dateCreated
                heroImage {
                    ... on heroImage_heroImage_BlockType {
                        id
                        image {
                            ...Image
                        }
                    }
                }
            }
        }
    }
}
