#import "~/gql/fragments/Image"

query HelpTopicDetail($slug: [String!]) {
    entry(section: "meapProject", slug: $slug) {
        id
        title
        summary
        heroImage {
            ... on heroImage_heroImage_BlockType {
                id
                image {
                    ...Image
                }
                altText
            }
        }
        meapProjectCallToAction
        titleGeneral
        projectDescription
        citation
        projectContributorsSubheading
        projectContributors
        projectType
        region
        meapProjectTopic
        institution
        languageOfOrigin
        format
        periodDateRange
    }
}
